### ISSUE TITLE
mozilla webidl files?

### ISSUE THREAD

**Issue by adrian-rt** [rustwasm/weedle#29]
### Summary

can this be used to parse Firefox' webidl files?

Sorry for this, I'm a beginner in rust & webidl. I basically want to parse webidl files from firefox/Chrome/Chakra etc

### Additional Details

Provide any additional details here.

**Comment by fitzgen** [comment]
Yes, in fact the Web IDL files we use to generate `web-sys` originate from mozilla-centeral
