### ISSUE TITLE
how to run ?

### ISSUE THREAD

**Issue by adrian-rt** [rustwasm/weedle#30]
### Summary

Hi,

how do you run this ?

It's my first rust project ever. thanks.

### Additional Details

Provide any additional details here.

**Comment by fitzgen** [comment]
This library is used as part of the `wasm-bindgen-webidl` crate, so if you want some examples that is probably the best place to look: https://github.com/rustwasm/wasm-bindgen/blob/8775f9b1b33938cd1fcf94d9162ea23c30d8f76f/crates/webidl/src/lib.rs#L50
