### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by benesch** [rustwasm/weedle#36]
Hey @alexcrichton, any chance of a new release of this that includes https://github.com/rustwasm/weedle/pull/35? This is the last crate in our dependency graph that still depends on nom v4 (and as a result version_check 0.1.5).

**Comment by alexcrichton** [comment]
Sure thing, done now!

**Comment by benesch** [comment]
I don't know where you find the time to maintain all these crates, but I'm sure glad you do! ❤️ Thanks very much.
